# Generated by Django 4.2.1 on 2023-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propretyreview',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
