# Generated by Django 4.2.1 on 2023-06-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0002_propretyreview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprety',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_prt', to='propreties.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proprety',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_prt', to='propreties.place'),
        ),
    ]
