# Generated by Django 4.2.1 on 2023-06-04 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0003_proprety_category_alter_proprety_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprety',
            name='createdat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proprety',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
