# Generated by Django 4.2.1 on 2023-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0004_proprety_createdat_proprety_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprety',
            name='desc',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
