# Generated by Django 4.2.1 on 2023-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_do', models.TextField(max_length=1000)),
                ('our_miss', models.TextField(max_length=1000)),
                ('our_goal', models.TextField(max_length=1000)),
                ('img', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=160)),
                ('descr', models.TextField(max_length=1000)),
            ],
        ),
    ]
